server:
  port: 8081

spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    topic-name: test-topic
    queue-name: test-queue
  application:
    name: publisher
